### ISSUE TITLE
no cookie retrieved, object reference not set to an instance of an object

### ISSUE THREAD

**Issue by bbregman** [FabioCuneaz/Cookie365#1]
the msohrdurl response is not only the ADFS endpoint url, but nowadays also contains the wtrealm and wa querysting parameters including their values. cookie365.exe shouldn't append those parameters anymore, since they are already filled in when obtaining the response from userrealm.srf -> source code change to provide a solution for this error: 
spoauthutility.cs - line 398
//ub.Query = String.Format("{0}&wa=wsignin1.0&wtrealm=urn:federation:MicrosoftOnline", this.adfsAuthUrl.Query.Remove(0, 1)).
//    Replace("&username=", String.Format("&username={0}", this.username));
ub.Query = String.Format("{0}", this.adfsAuthUrl.Query.Remove(0, 1)).
                         Replace("&username=", String.Format("&username={0}", this.username));

**Comment by FabioCuneaz** [comment]
Hi BBREGMAN. Thank you. I found out the same issue same days ago. I released a new version which fixes the issue [here](https://fabiocuneaz.blogspot.it) In the next weekend I will also update github source code.

Thank you very much for pinpointing the solution. If you posted some days ago I would saved me some work :-)

**Comment by FabioCuneaz** [comment]
Should be fixed. Published updated code
