### ISSUE TITLE
Code not working in my environment

### ISSUE THREAD

**Issue by Jaime42** [FabioCuneaz/Cookie365#2]
This looks to be possibly a great app.  I tried to get it to work in my environment, but I receive the below output:

[ERROR]:An error occurred while sending the request.
[ERROR]:One or more errors occurred.

Any suggestions?

**Comment by FabioCuneaz** [comment]
It seems the http POST to your ADFS sign-in URL is failing. I published a pre-release of version 0.8 which adds a "-debug" switch to get more information. Could you try and let me know if you get more details about the error ?
https://github.com/FabioCuneaz/Cookie365/releases/tag/0.8

Regards.

**Comment by Jaime42** [comment]
Here is the updated output, using 0.8:

SharePoint URL: https://dubuque-my.sharepoint.com
User: jhabel@dbqschools.org
Use Windows Integrated Authentication: True
HomeDir: DavWWWRoot\personal\jhabel_dbqschools_org\Documents
Mount as disk: O:
Retrieving ADFS URL...[OK]
ADFS PROXY URL=[https://adfs.dbqschools.org/adfs/ls/?username=jhabel%40dbqschools.org&wa=wsignin1.0&wtrealm=urn:federation:MicrosoftOnline&wctx=]
FORMAT=[username=jhabel%40dbqschools.org&wa=wsignin1.0&wtrealm=urn%3afederation%3aMicrosoftOnline&wctx=&wa=wsignin1.0&wtrealm=urn:federation:MicrosoftOnline]
Logging in and retrieving SAML Token...URL=[https://adfs.dbqschools.org/adfs/ls/auth/integrated/?username=jhabel%40dbqschools.org&wa=wsignin1.0&wtrealm=urn:federation:MicrosoftOnline&wctx=]  System.Byte[]
[OK]
Retrieving STS Token...[OK]
Retrieving Cookies....[ERROR]:An error occurred while sending the request.
[ERROR]:One or more errors occurred.

**Comment by FabioCuneaz** [comment]
It looks like a networking issue. Seems to me your ADFS proxy is not reachable . If I try to telnet to adfs.dbqschools.org on port 443, I get no answer. You should check the connectivity from the client to your adfs proxy.

**Comment by FabioCuneaz** [comment]
OK. The dev env is hosted on Azure in the Netherlands. I suggest to get in contact via email to share the details in private. You can find my contact on linkedin and ask for contact. Regards, Fabio

**Comment by FabioCuneaz** [comment]
Hello Jaime, you were right. There were issues related to the expiration of cookies in your timezone. I should have fixed with release 1.0: https://github.com/FabioCuneaz/Cookie365/releases/tag/1.0
Thank you

**Comment by FabioCuneaz** [comment]
Issue fixed with the latest release.
